### ISSUE TITLE
Modificar partícula de les anelles de l'angel mag.

### ISSUE THREAD

**Issue by PauFlorenti** [DreamSlash/RegicideX#10]
**Summary**
Cal refer la partícula de l'atac en anells que genera l'àngel mag.

**Acceptance Criteria**
Partícules decents.

**Comment by PabloAcedo** [comment]
No hay particulas ahora no? solo el anillo ese feo

**Comment by PauFlorenti** [comment]
Siii, pero molaria poder dar algún efecto xulo con el Niagra. Una onda expansiva o algo, y no un anillo opaco.

**Comment by PauFlorenti** [comment]
Algo así estaría interesante @PabloAcedo 
https://www.youtube.com/watch?v=N-d3G6WeI-A
