### ISSUE TITLE
Combo counter UI

### ISSUE THREAD

**Issue by AlvarAlonso** [DreamSlash/RegicideX#117]
**Summary**
There is no way to know how long the player is into a combo. Some widget has to be added to give feedback about combo progress.

**Acceptance Criteria**
- [ ] Small widget in the right side of the screen containting a counter.
- [ ] The counter has to be updated with each consecutive hit.
- [ ] Different widget styles depending on the accumulated score of the combo.

**Comment by PauFlorenti** [comment]
Won't do
