### ISSUE TITLE
Auto assist

### ISSUE THREAD

**Issue by PauFlorenti** [DreamSlash/RegicideX#33]
**Summary**
Apply and auto assist for the player when attacking. It should help direct the hit to the nearby enemy.

Todo:
- [x] Do not take into account enemies that are in opposite directions from the user movement input.
- [x] Air combat assist.

**Comment by AlvarAlonso** [comment]
A first iteration of the autoassist is already done and working. Improved mobility while using combos (can rotate between attacks) and air assist.
