### ISSUE TITLE
Saltar cinemàtiques des de mando

### ISSUE THREAD

**Issue by PauFlorenti** [DreamSlash/RegicideX#4]
**Summary**
Poder saltar totes les cinemàtiques des d'un mando.
Es proposa saltar amb la X en cas de mando de PlayStation.

**Acceptance Criteria**
- [x] Salta la cinemàtica amb el botó X.

**Comment by PabloAcedo** [comment]
Y con el A de la Xbox?

**Comment by PauFlorenti** [comment]
Si, es una opción. Lo que no sé como mappear según el mando. Tendré que investigar. Pero:
 - Xbox: A
 - PS4: X
