### ISSUE TITLE
Navegació amb mando pels menús

### ISSUE THREAD

**Issue by PauFlorenti** [DreamSlash/RegicideX#8]

**Comment by AlvarAlonso** [comment]
De moment ho estic fent tot en BP.

Els inputs són rebuts des d'un controller, no des dels inputs de UI. Aquest controller és un actor que s'ha de posar en l'escena. Els seus inputs estan marcats perquè es cridin quan el joc està en pause també.

![Image](https://user-images.githubusercontent.com/74962261/218262476-6acf5024-582d-4f1d-8e49-b7b8d9a67863.png)

De moment escolta a events de les fletxetes del mando cap amunt i cap avall i la X per seleccionar.

Aquests events es redirigeixen al Widget al que s'està fent focus, que deriva d'una classe pare anomenada WBP_NavigationUserWidget, que gestiona l'input i la navegació del menú.

![Image](https://user-images.githubusercontent.com/74962261/218262557-58d3dc5a-6743-42c9-a659-23b51d95b5b5.png)

Aquesta classe té funcionalitat per recorrer una array de buttons i porta l'índex del que està actualment activat. També és l'encarregada de donar estils als buttons perquè es mostri quin tenim "hovered" o quin seleccionem.

Les classes filles emplenen l'array i el map amb la info dels buttons que tenen i són les que tenen les funcions que els buttons cridaràn quan els cliquem. És guarro això últim, ja es canviarà.

![Image](https://user-images.githubusercontent.com/74962261/218262607-d3ed1418-c286-41bb-bb12-44be260473ea.png)

**Comment by AlvarAlonso** [comment]
Estic refactoritzant tot a C++. També estic fent un sistema perquè poguem construir UI de manera còmode utiltizant només C++. No haurem de hardcodejar tot com està fins ara, i serà útil per quan afegim més pantalles, com menús d'opcions, de score, modes de joc, etc...

**Comment by AlvarAlonso** [comment]
Tot això ha quedat obsolet des de que vaig crear la solució de C++.
