### ISSUE TITLE
En el menú es pot prèmer el botó múltiples cops abans de que acabi l'acció

### ISSUE THREAD

**Issue by PauFlorenti** [DreamSlash/RegicideX#9]
**Describe the bug**
En els menus, si prémem el botó i l'acció no s'ha realitzat encara, el joc segueix rebent els inputs fent que es puguin repetir sons o accions.

**To Reproduce**
1. Go to 'qualsevol menu del joc'
2. Click on 'qualsevol botó, "Exit" per exemple'
3. Fes click altre cop abans de que es fagi l'acció.
4. El so es repeteix quan no hauría.

**Expected behavior**
Un cop es prem un botó del menú no es pot agafar cap més input fins que s'hagi dut a terme l'acció.

**Comment by AlvarAlonso** [comment]
It's done.
